extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - plugin:jest/recommended
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaVersion: 12
    sourceType: module
plugins:
    - "@typescript-eslint"
    - jest
rules:
    indent:
        - error
        - 4
    semi:
        - error
        - never
    no-shadow: off
    "@typescript-eslint/no-shadow":
        - error
    no-use-before-define: off
    "@typescript-eslint/no-use-before-define":
        - error
env:
    jest/globals: true
